In [4]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import os

In [5]:
URL = 'https://www.iplt20.com/stats/2021/mostRuns?stats_type=batting'

In [6]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',
}

In [7]:
page = requests.get(URL, headers=headers)

In [8]:
soup = BeautifulSoup(page.content,"html.parser")

In [9]:
for table in soup.find_all('table'):
    print(table.get('class'))

['np-mostruns_table']
['np-mostruns_table']
['ih-td-tab']

In [10]:
table=soup.find('table',class_= 'np-mostruns_table')

In [43]:
df = pd.DataFrame(columns=["POS","Player","Mat","Inns","NO","Runs","HS","Avg","BF","SR","100","50","4s","6s"])

In [44]:
for row in table.find_all('tr'):
    columns=row.find_all('td')
    if (columns!=[]):
        POS = columns[0].text.strip()
        Player = columns[1].text.strip()
        Mat = columns[2].text.strip()
        Inns = columns[3].text.strip('&0.')
        NO = columns[4].text.strip('&0.')
        Runs = columns[5].text.strip('&0.')
        HS = columns[6].text.strip('&0.')
        Avg = columns[7].text.strip('&0.')
        BF = columns[8].text.strip('&0.')
        SR = columns[9].text.strip('&0.')
        Hundred = columns[10].text.strip()
        Fifty = columns[11].text.strip()
        fourW = columns[12].text.strip('&0.')
        fiveW = columns[13].text.strip('&0.')

        df = df.append({"POS":POS,'Player':Player,'Mat':Mat,'Inns':Inns,'NO':NO,'Runs':Runs,'HS':HS,'Avg':Avg,'BF':BF,'SR':SR,"100":Hundred,"50":Fifty,"4s":fourW,"6s":fiveW}, ignore_index=True)

In [46]:
df

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Ruturaj Gaikwad,16,16,2,635,101,45.35,466,136.26,1,4,64,23
1,2,Faf du Plessis,16,16,2,633,95,45.21,458,138.2,0,6,6,23
2,3,KL Rahul,13,13,3,626,98,62.6,451,138.8,0,6,48,3
3,4,Shikhar Dhawan,16,16,1,587,92,39.13,471,124.62,0,3,63,16
4,5,Glenn Maxwell,15,14,2,513,78,42.75,356,144.1,0,6,48,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,145,Kuldip Yadav,1,1,1,,,,4,,0,0,,
145,146,Sarfaraz Khan,2,2,,,,,4,,0,0,,
146,147,Anuj Rawat,2,1,,,,,1,,0,0,,
147,148,Jimmy Neesham,3,2,,,,,2,,0,0,,
148,149,Piyush Chawla,1,1,,,,,2,,0,0,,

In [48]:
MostRunsWiDS=df.to_csv('df.csv', index=False)

In [49]:
df.to_excel(r'MostRunsWiDS.xlsx', index = False)